version: '1.0'
kind: pipeline
metadata:
  name: ngci-test/pipeline-creator
  description: "Pipeline creator for pipeline-spec.yml files"
  deprecate: {}
  project: ngci-test
spec:
  triggers:
    - type: git
      provider: github
      name: path-trigger
      repo: rfblue2/ngci-test
      context: "github"
      contexts: []
      events:
        - push.heads
      branchRegex: /.*/gi
      modifiedFilesGlob: {'**/pipeline-spec.yml', 'create_pipelines.sh'}
      disabled: false
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
  contexts: []
  variables: []
  steps:
    main_clone:
      title: 'Cloning main repository...'
      type: git-clone
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      revision: '${{CF_REVISION}}'
      git: github
    pipelineCreator:
      title: Setting up a new pipeline programatically
      image: codefresh/cli
      commands:
        - ./create_pipelines.sh
  stages: []
