# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  trigger-workflows:
    type: boolean
    default: true
  test-project1:
    type: boolean
    default: false
  test-project2:
    type: boolean
    default: false  
jobs:
  trigger-workflows:
    docker:      
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x ./.circleci/circle_trigger.sh && ./.circleci/circle_trigger.sh
  run-test:
    parameters:
      test-target:
        type: string
    docker:
      - image: l.gcr.io/google/bazel:3.1.0
    steps:
      - checkout
      - run: bazel test << parameters.test-target >>  
workflows:
  trigger-workflows:
    when: << pipeline.parameters.trigger-workflows >>
    jobs:
      - trigger-workflows
  test-project1:
    when: << pipeline.parameters.test-project1 >>
    jobs:
      - run-test:
          test-target: //project1/...:all  
  test-project2:
    when: << pipeline.parameters.test-project2 >>
    jobs:
      - run-test:
          test-target: //project2/...:all