# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  trigger:
    type: boolean
    default: true
jobs:
  trigger-workflows:
    docker:      
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: echo 'hello' #chmod +x ./circle_trigger.sh && ./circle_trigger.sh
  test-project1:
    docker:
      - image: l.gcr.io/google/bazel:3.1.0
    steps:
      - checkout
      - run: bazel test //project1/...:all
workflows:
  pre-submit:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
      - test-project1
